const GET_COUNTRIES = "GET_COUNTRIES";
const GET_ACTIVITIES = "GET_ACTIVITIES";
const GET_DETAIL = "GET_DETAIL";
const SET_LOADING = "SET_LOADING"
const RESET_DETAIL = "RESET_DETAIL"

module.exports = {
    GET_COUNTRIES,
    GET_ACTIVITIES,
    GET_DETAIL,
    SET_LOADING,
    RESET_DETAIL
}